# dir with genome fasta files
genome_fasta: path/to/dir/with/MAGs/in/fasta/format/MAG.fasta

# output dir
output_dir: path/to/output/dir

# training file
training_file: path/to/training/file/training.trn

# path to bakta DB:
bakta_db: path/to/bakta/DB
